[package]
name = "scl"
version = "0.0.1"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
pest = "^1.0.0"
pest_derive = "^1.0.0"

[dev-dependencies]
tempdir = "0.3"
pretty_assertions = "0.5"
